name: static resume app

on:
  push:
    branches:
      - main

jobs:
  build:
    name:  Build Stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust to your app's version

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build  # Assumes output is in ./dist

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: .

  deploy:
    name: Deploy Stage
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Copy files to EC2
        run: |
          scp -i ec2_key.pem -o StrictHostKeyChecking=no -r . ${{ secrets.EC2_HOST }}:${{ secrets.EC2_APP_PATH }}

      - name: Restart app on EC2
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} << 'EOF'
            cd ${{ secrets.EC2_APP_PATH }}
            pm2 restart all || sudo systemctl restart myapp.service
          EOF
